name: CI & Deploy Reporting

on:
  push:
    paths:
      - 'reporting/**'
      - 'dags/dag_reporting_and_dashboard.py'

jobs:
  test-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run reporting tests
        run: pytest reporting --maxfail=1 --disable-warnings -q

  build-and-deploy:
    needs: test-report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.REGISTRY_URL }}/anomaly-report:latest

      - name: Deploy to Kubernetes
        uses: azure/k8s-d
