# 데이터베이스 연결 URI (SQLAlchemy 형식)
db_uri: "postgresql://username:password@hostname:5432/dbname"

# 로그 조회 기간 (일 단위)
lookback_days: 1

# 리소스별 가중치 (피처 엔지니어링용)
resource_weights:
  confidential_doc: 5.0
  financial_record: 3.0
  public_info: 1.0

# 이상 탐지 모델 경로 및 하이퍼파라미터
model_path: "risk_iforest.joblib"
contamination: 0.02
n_estimators: 100
random_state: 42

# 드리프트 감지 활성화 (river ADWIN)
drift_detection: true

# 알림 설정
alertmanager_url: "http://alertmanager.company.local:9093"
flap_window_minutes: 5
flap_threshold: 3
dedup_window_minutes: 10
mute_rules:
  - alertname: "RiskAnomaly"
    severity: "info"

# 결과 저장 파일명
output_csv: "anomaly_results.csv"

# Prometheus 메트릭 서버 포트
metrics_port: 8000

# 자동 재학습 스케줄러 설정
enable_retrain_scheduler: true
retrain_hourly: 24
retrain_event_threshold: 5
retrain_event_window: 10
